### ISSUE TITLE
Add support for preact's class prop

### ISSUE THREAD

**Issue by DoMiNeLa10** [felipeochoa/rjsx-mode#101] opened 2019-05-01 09:38 UTC
Unlike react, [preact permits the use of a `class` prop for class names](https://preactjs.com/guide/differences-to-react#what-s-added-). `rjsx-mode` marks the use of the `class` prop as an "invalid JSX identifier" error. While this error message makes sense in the context of react, it should be possible to disable it for use with other libraries that permit this prop in JSX.

**Comment by felipeochoa** [comment] 2019-05-01 13:19
Duplicate of #62

**Closed by felipeochoa** 2019-05-01 13:19 UTC
