### ISSUE TITLE
prop `in` breaks rjsx-mode parsing

### ISSUE THREAD

**Issue by pcr910303** [felipeochoa/rjsx-mode#115] opened 2019-08-02 16:23 UTC
The prop `in` makes rjsx-mode not recognize the prop.

<img width="289" alt="스크린샷 2019-08-03 오전 1 23 06" src="https://user-images.githubusercontent.com/37990858/62384388-438f6d00-b58d-11e9-82d8-f5db7b29729f.png">

**Comment by felipeochoa** [comment] 2019-08-02 21:32
Duplicate of #62

**Closed by felipeochoa** 2019-08-02 21:32 UTC
